// <auto-generated />
using System;
using KiVenda.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiVenda.Persistence.Migrations
{
    [DbContext(typeof(KiVendaDbContext))]
    [Migration("20260822095147_InicialCreate")]
    partial class InicialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("KiVenda.Core.Auditoria.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosAntes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosDepois")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadeAfetada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UtilizadorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataHora");

                    b.HasIndex("UtilizadorId");

                    b.HasIndex("EntidadeAfetada", "EntidadeId");

                    b.ToTable("LogsAuditoria", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Caixa.MovimentoCaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrigemVendaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessaoCaixaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UtilizadorId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("OrigemVendaId");

                    b.HasIndex("SessaoCaixaId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("MovimentosCaixa", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Caixa.SessaoCaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFecho")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Divergencia")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SaldoFinalInformado")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UtilizadorAberturaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UtilizadorFechoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataAbertura");

                    b.HasIndex("Estado");

                    b.HasIndex("UtilizadorAberturaId");

                    b.HasIndex("UtilizadorFechoId");

                    b.ToTable("SessoesCaixa", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Compras.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UtilizadorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Compras", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Compras.ItemCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApresentacaoProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompraId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoTotalItem")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantidadeNaApresentacao")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantidadeUnidadeBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApresentacaoProdutoId");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensCompra", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Fornecedores.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutosFornecidos")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Fornecedores", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.ApresentacaoProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FatorConversaoParaUnidadeBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasFilter("[CodigoBarras] IS NOT NULL");

                    b.HasIndex("ProdutoId", "Ativa");

                    b.ToTable("ApresentacoesProduto", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId", "Codigo")
                        .IsUnique();

                    b.ToTable("Lotes", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.MovimentoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CustoUnitarioUnidadeBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Origem")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OrigemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UtilizadorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("OrigemId");

                    b.HasIndex("UtilizadorId");

                    b.HasIndex("ProdutoId", "Data");

                    b.ToTable("MovimentosStock", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoMedioPonderado")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstoqueAtual")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoVendaPorUnidadeBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnidadeBaseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasFilter("[CodigoBarras] IS NOT NULL");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("Nome");

                    b.HasIndex("UnidadeBaseId");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.UnidadeMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("UnidadesMedida", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Utilizadores.Utilizador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUtilizador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomeUtilizador")
                        .IsUnique();

                    b.ToTable("Utilizadores", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Vendas.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApresentacaoProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoUnitarioUnidadeBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitarioUnidadeBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantidadeNaApresentacao")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantidadeUnidadeBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VendaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApresentacaoProdutoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensVenda", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Vendas.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VendaId");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Vendas.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessaoCaixaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UtilizadorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Data");

                    b.HasIndex("SessaoCaixaId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("KiVenda.Core.Auditoria.LogAuditoria", b =>
                {
                    b.HasOne("KiVenda.Core.Utilizadores.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KiVenda.Core.Caixa.MovimentoCaixa", b =>
                {
                    b.HasOne("KiVenda.Core.Vendas.Venda", null)
                        .WithMany()
                        .HasForeignKey("OrigemVendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KiVenda.Core.Caixa.SessaoCaixa", null)
                        .WithMany("Movimentos")
                        .HasForeignKey("SessaoCaixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KiVenda.Core.Utilizadores.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KiVenda.Core.Caixa.SessaoCaixa", b =>
                {
                    b.HasOne("KiVenda.Core.Utilizadores.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UtilizadorAberturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KiVenda.Core.Utilizadores.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UtilizadorFechoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KiVenda.Core.Compras.Compra", b =>
                {
                    b.HasOne("KiVenda.Core.Fornecedores.Fornecedor", null)
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KiVenda.Core.Utilizadores.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KiVenda.Core.Compras.ItemCompra", b =>
                {
                    b.HasOne("KiVenda.Core.Produtos.ApresentacaoProduto", null)
                        .WithMany()
                        .HasForeignKey("ApresentacaoProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KiVenda.Core.Compras.Compra", null)
                        .WithMany("Itens")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KiVenda.Core.Produtos.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.ApresentacaoProduto", b =>
                {
                    b.HasOne("KiVenda.Core.Produtos.Produto", null)
                        .WithMany("Apresentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.Lote", b =>
                {
                    b.HasOne("KiVenda.Core.Produtos.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.MovimentoStock", b =>
                {
                    b.HasOne("KiVenda.Core.Produtos.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KiVenda.Core.Produtos.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KiVenda.Core.Utilizadores.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.Produto", b =>
                {
                    b.HasOne("KiVenda.Core.Produtos.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KiVenda.Core.Produtos.UnidadeMedida", null)
                        .WithMany()
                        .HasForeignKey("UnidadeBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KiVenda.Core.Vendas.ItemVenda", b =>
                {
                    b.HasOne("KiVenda.Core.Produtos.ApresentacaoProduto", null)
                        .WithMany()
                        .HasForeignKey("ApresentacaoProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KiVenda.Core.Produtos.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KiVenda.Core.Vendas.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KiVenda.Core.Vendas.Pagamento", b =>
                {
                    b.HasOne("KiVenda.Core.Vendas.Venda", null)
                        .WithMany("Pagamentos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KiVenda.Core.Vendas.Venda", b =>
                {
                    b.HasOne("KiVenda.Core.Clientes.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KiVenda.Core.Caixa.SessaoCaixa", null)
                        .WithMany()
                        .HasForeignKey("SessaoCaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KiVenda.Core.Utilizadores.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KiVenda.Core.Caixa.SessaoCaixa", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("KiVenda.Core.Compras.Compra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("KiVenda.Core.Produtos.Produto", b =>
                {
                    b.Navigation("Apresentacoes");
                });

            modelBuilder.Entity("KiVenda.Core.Vendas.Venda", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
