using KiVenda.Application.Abstractions.Persistence;
using KiVenda.Core.Clientes;
using KiVenda.Core.Exceptions;
using KiVenda.Core.Fornecedores;
using KiVenda.Core.Funcionarios;
namespace KiVenda.Application.Cadastros;
public sealed record ClienteCadastroDto(Guid Id,string Nome,string? Telefone,string? Email,string? Nif);
public sealed record FornecedorCadastroDto(Guid Id,string Nome,string? Telefone,string? Email,string? Nif,string? ProdutosFornecidos);
public sealed record FuncionarioDto(Guid Id,string Codigo,string Nome,string? Telefone,string? Email,string? BI,string? Cargo,string? Departamento,string? Turno,DateTime DataAdmissao,decimal SalarioBase,bool Ativo);
public sealed class ListarClientesCadastroUseCase(IUnitOfWork uow){public async Task<IReadOnlyList<ClienteCadastroDto>> ExecutarAsync(string? termo=null,CancellationToken ct=default)=>(await uow.Clientes.ListarAsync(termo,ct)).Select(x=>new ClienteCadastroDto(x.Id,x.Nome,x.Telefone,x.Email,x.Nif)).ToList();}
public sealed class GuardarClienteCadastroUseCase(IUnitOfWork uow){public async Task ExecutarAsync(Guid? id,string nome,string? telefone,string? email,string? nif,CancellationToken ct=default){if(id is null)await uow.Clientes.AdicionarAsync(new Cliente(nome,telefone,email,nif),ct);else{var x=await uow.Clientes.ObterPorIdAsync(id.Value,ct)??throw new DomainException("Cliente não encontrado.");x.EditarDados(nome,telefone,email,nif);}await uow.SaveChangesAsync(ct);}}
public sealed class EliminarClienteUseCase(IUnitOfWork uow){public async Task ExecutarAsync(Guid id,CancellationToken ct=default){var x=await uow.Clientes.ObterPorIdAsync(id,ct)??throw new DomainException("Cliente não encontrado.");uow.Clientes.Remover(x);await uow.SaveChangesAsync(ct);}}
public sealed class ListarFornecedoresCadastroUseCase(IUnitOfWork uow){public async Task<IReadOnlyList<FornecedorCadastroDto>> ExecutarAsync(string? termo=null,CancellationToken ct=default)=>(await uow.Fornecedores.ListarAsync(termo,ct)).Select(x=>new FornecedorCadastroDto(x.Id,x.Nome,x.Telefone,x.Email,x.Nif,x.ProdutosFornecidos)).ToList();}
public sealed class GuardarFornecedorCadastroUseCase(IUnitOfWork uow){public async Task ExecutarAsync(Guid? id,string nome,string? telefone,string? email,string? nif,string? produtos,CancellationToken ct=default){if(id is null)await uow.Fornecedores.AdicionarAsync(new Fornecedor(nome,telefone,produtos,email,nif),ct);else{var x=await uow.Fornecedores.ObterPorIdAsync(id.Value,ct)??throw new DomainException("Fornecedor não encontrado.");x.EditarDados(nome,telefone,produtos,email,nif);}await uow.SaveChangesAsync(ct);}}
public sealed class EliminarFornecedorUseCase(IUnitOfWork uow){public async Task ExecutarAsync(Guid id,CancellationToken ct=default){var x=await uow.Fornecedores.ObterPorIdAsync(id,ct)??throw new DomainException("Fornecedor não encontrado.");uow.Fornecedores.Remover(x);await uow.SaveChangesAsync(ct);}}
public sealed class ListarFuncionariosUseCase(IUnitOfWork uow){public async Task<IReadOnlyList<FuncionarioDto>> ExecutarAsync(string? termo=null,CancellationToken ct=default)=>(await uow.Funcionarios.ListarAsync(termo,ct)).Select(x=>new FuncionarioDto(x.Id,x.Codigo,x.Nome,x.Telefone,x.Email,x.BI,x.Cargo,x.Departamento,x.Turno,x.DataAdmissao,x.SalarioBase,x.Ativo)).ToList();}
public sealed class GuardarFuncionarioUseCase(IUnitOfWork uow){public async Task ExecutarAsync(Guid? id,string nome,string? telefone,string? email,string? bi,string? cargo,string? departamento,string? turno,DateTime dataAdmissao,decimal salarioBase,bool ativo,CancellationToken ct=default){if(id is null){var codigo=await uow.Funcionarios.ObterProximoCodigoAsync(ct);await uow.Funcionarios.AdicionarAsync(new Funcionario(codigo,nome,telefone,email,bi,cargo,departamento,turno,dataAdmissao,salarioBase,ativo),ct);}else{var x=await uow.Funcionarios.ObterPorIdAsync(id.Value,ct)??throw new DomainException("Funcionário não encontrado.");x.EditarDados(nome,telefone,email,bi,cargo,departamento,turno,dataAdmissao,salarioBase,ativo);}await uow.SaveChangesAsync(ct);}}
public sealed class EliminarFuncionarioUseCase(IUnitOfWork uow){public async Task ExecutarAsync(Guid id,CancellationToken ct=default){var x=await uow.Funcionarios.ObterPorIdAsync(id,ct)??throw new DomainException("Funcionário não encontrado.");uow.Funcionarios.Remover(x);await uow.SaveChangesAsync(ct);}}